name: mi
channels:
  - conda-forge
  - huggingface
  - pytorch
	- nvidia
dependencies:
  - python=3.11
  - numpy
  - pandas
  - notebook
  - scikit-learn
  - altair-all
  - pytorch
	- pytorch-cuda=12.1
  - transformers
  - datasets
  - pip
  - pip:
    - transformer_lens
