name: mi
channels:
  - conda-forge
  - huggingface
  - pytorch
dependencies:
  - python=3.11
  - numpy
  - pandas
  - notebook
  - scikit-learn
  - altair-all
  - pytorch
  - transformers
  - datasets
  - pip
  - pip:
      - transformer_lens
      - einsum
