name: mi
channels:
  - conda-forge
  - huggingface
  - pytorch-nightly
  - nvidia
dependencies:
  - python=3.11
  - numpy
  - pandas
  - notebook
  - scikit-learn
  - altair-all
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - transformers
  - datasets
  - pip
  - pip:
      - transformer_lens
      - einsum
